### ISSUE TITLE
spasm creates a binary regardless of running into an error

### ISSUE THREAD

**Issue by gpadd** [alberthdev/spasm-ng#33]
I've had this happen to me a couple of times, it's not really, REALLY bad.
But in case you just were not reading the error messages or pipe them to /dev/null or something it can cause some confusion to the one trying to use it, immediately after or some time later.

I'm using the current version but I might as well add this to the issue.
"Version v0.5-beta.2 (built on Apr  7 2016 @ 20:11:23)" from git.

**Comment by alberthdev** [comment]
Thanks for the report! Do you have a test case that triggers this issue?

Also, if you want to report the version, run `make version`, then `make` - and provide both the version and Git revision. (I should probably document that somewhere...)

**Comment by gpadd** [comment]
No test case, it always happens it seems.

The current spasm-ng version is: v0.5-beta.2.git20160409
Git revision: 61d8ff5

**Comment by alberthdev** [comment]
This looks like it's fixed via PR #35 - closing! Feel free to re-open if this is still an issue.

**Comment by alberthdev** [comment]
It looks like the PR didn't work as expected - it caused first pass issues to stop the assembler, which shouldn't happen. (I didn't realize this until @jacobly0 pointed it out, so thanks for the heads up!)

@C-Elegans / @gpadd, could any of you provide a test case for this issue?

**Comment by C-Elegans** [comment]
Possible testcase:
```
start:
    jr end
    jmp end
    jp doesntexist
    .fill 128
end:
```
This causes 3 errors, 1 in the first pass and 2 in the second pass.

**Comment by C-Elegans** [comment]
Why is the first pass giving an error on the macro expansion testcase if there is no error?

**Comment by alberthdev** [comment]
> Why is the first pass giving an error on the macro expansion testcase if there is no error?

I believe the error is generated because the macro expansion is a bit fuzzy for the first pass, and it doesn't correctly resolve until we hit the second pass. If the second pass fails to resolve, then the macro does not exist, and we can correctly error on that part.

> Possible testcase:

Thanks for the testcase! Regarding the test case (and any other files you might have), could you test again with the latest code? I think I might have fixed this issue in commit 5e96d009, which only exits if `nSession == 1` (which is when the errors that are supposed to be visible are printed). From the original code (before changes were made), errors that are above 1 are not printed because of the pass system and levels in place.

**Comment by C-Elegans** [comment]
Your change seems to have fixed it.

**Comment by alberthdev** [comment]
Awesome! :smile: This was a pretty interesting bug to fix, so thanks for bearing with me during all of this! Since this is fixed, I'll go ahead and close this issue - but if you find any strange cases that don't result in an exit after an error, feel free to re-open!
