### ISSUE TITLE
[informative] homebrew keg for spasm-ng

### ISSUE THREAD

**Issue by jfmherokiller** [alberthdev/spasm-ng#39]
i created a little homebrew keg for installing spasm-ng on osx.
it can be found [here](https://github.com/jfmherokiller/homebrew-tap/blob/master/Formula/spasm-ng.rb).

**Comment by adriweb** [comment]
Nice!

**Comment by jfmherokiller** [comment]
i hope it helps in some way

**Comment by alberthdev** [comment]
@jfmherokiller One thing to note - we do have a `make check` that you can use for the build process to verify that all of our tests are passing before installing!

Other than that, good work on the packaging - reading about these package files, maybe it would be wise to set up a central repository for hosting packaging scripts. Since you are knowledgeable in this space, would you like to manage the OS X side of things for us?

**Comment by jfmherokiller** [comment]
well i dont know if i can handle everything i kinda just whipped the brew file up because i prefer installing stuff using homebrew instead of manually from source every time
