### ISSUE TITLE
String macro arguments

### ISSUE THREAD

**Issue by jacobly0** [alberthdev/spasm-ng#42]
Passing a string to a macro now errors, for example:

    $ cat string-argument.asm
    #define string(value) .db value,0
    string("test")
    $ spasm string-argument.asm 
    Pass one... 
    string-argument.asm:2: error SE105: Unrecognized value prefix '"'

This was introduced by @C-Elegans in either 248fe931a0b53158fae1f9171494431c09433219 or 1898492847d88eadec785f83474342604bb5106f.

**Comment by C-Elegans** [comment]
It looks like previous versions do produce an error that is not printed, my PR just exits when it encounters an error. After applying this patch to commit 9b20cef 
```
From 02a650143faae5ffd3dc8400aacf1a358542a802 Mon Sep 17 00:00:00 2001
From: C-Elegans <mtnolan2640@gmail.com>
Date: Sat, 25 Mar 2017 11:14:46 -0400
Subject: [PATCH] Print errors

---
 errors.cpp | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/errors.cpp b/errors.cpp
index 49755e1..25b7123 100644
--- a/errors.cpp
+++ b/errors.cpp
@@ -359,7 +359,7 @@ static void SetLastSPASMProblem(DWORD dwErrorCode, bool fIsWarning, va_list vali
 
 	//if (suppress_errors == false)
 	//{
-		//PrintSPASMError(lpErr);
+		PrintSPASMError(lpErr);
 	//}
 }
 
-- 
2.12.0

```

The output is as follows:
```
$ cat string-argument.asm
#define string(value) .db value,0
string("test")
$ spasm string-argument.asm string-argument.bin
Pass one...
string-argument.asm:2: error SE105: Unrecognized value prefix '"'
string-argument.asm:2: error SE105: Unrecognized value prefix '"'
Pass two...
Assembly time: 0.041 seconds
$ hexdump string-argument.bin
000000 74 65 73 74 00
0000005
```

**Comment by alberthdev** [comment]
Yeah, might have made a few mistakes when implementing this on my side as well...

@C-Elegans: Those errors probably shouldn't be printed out, actually... given that SPASM actually outputs a valid binary file! It looks like the first pass shouldn't be outputting anything at all, since it's just a quick look through before the second pass resolves any references.

Latest commit should fix this issue, so closing this! That said, I'm reopening #33 to continue the discussion on what cases should result in an error + exit.
