### ISSUE TITLE
Typedefs conflicts in modp_ascii.cpp

### ISSUE THREAD

**Issue by adriweb** [alberthdev/spasm-ng#6]
In `modp_ascii.cpp`, at [lines 45-46](https://github.com/alberthdev/spasm-ng/blob/master/modp_ascii.cpp#L45-L46), we can see:
```
typedef char uint8_t;
typedef int uint32_t;
```
This breaks the build, at least on OS X, because :

```
modp_ascii.cpp:45:14: error: typedef redefinition with different types ('char' vs 'unsigned char')
typedef char uint8_t;
             ^
/usr/include/_types/_uint8_t.h:31:23: note: previous definition is here
typedef unsigned char uint8_t;
                      ^
modp_ascii.cpp:46:13: error: typedef redefinition with different types ('int' vs 'unsigned int')
typedef int uint32_t;
            ^
/usr/include/_types/_uint32_t.h:31:22: note: previous definition is here
typedef unsigned int uint32_t;
```

Commenting those lines makes the build OK, but I'm not sure if the behaviour is correct for the code...

**Comment by alberthdev** [comment]
Hi! First and foremost, thanks for testing this stuff out on Mac OS X! I don't have any access to the Mac side of things, so it helps to hear feedback from OS X users - I'm grateful for any feedback on your side!

Potential Fix
===========
This might be a bit of a dirty way to approach it, but try replacing:
```
typedef char uint8_t;
typedef int uint32_t;
```
...with:
```
#ifndef UINT8_MAX
       typedef char uint8_t;
#endif
#ifndef UINT32_MAX
       typedef int uint32_t;
#endif
```
These checks should hopefully ensure that `uint8_t`/`uint32_t` was not previously defined before attempting to typedef it.

Please test this, and let me know what happens!

If possible, please also provide:

  * the method you took to compile the entire spasm-ng program (XCode? Some make command?),
  * the compiling command for this file (gcc/clang/etc, generally outputted when compiling with the Makefile),
  * the corresponding GCC/Clang/etc. version,
  * and finally, the OS X version you are currently using at the moment.

If you want to see interesting technical details, keep on reading!
**(If you do end up reading below, please also try to compile and run the two test programs provided below!)**

Investigation
===========
As for the problem, it's quite interesting to see - on Linux (one of the closer platforms to Mac OS X), there's also a similar conflicting definition:
```
$ egrep -r "uint8_t|uint32_t" /usr/include/ | grep unsigned
...
/usr/include/i386-linux-gnu/bits/types.h:typedef unsigned char __uint8_t;
/usr/include/i386-linux-gnu/bits/types.h:typedef unsigned int __uint32_t;
/usr/include/stdint.h:typedef unsigned char		uint8_t;
/usr/include/stdint.h:typedef unsigned int		uint32_t;
...
```

Then, the question is whether char/int are signed or unsigned. [Looking around](http://stackoverflow.com/a/2054959/1094484), it seems that GCC defaults the char to be signed. Microsoft also seems to make them [signed as well](https://msdn.microsoft.com/en-us/library/296az74e.aspx) (note the negative CHAR_MIN and INT_MIN).

Of course, rather than guess, I wrote a simple little test to check char/int signed-ness... with help of [good ol' StackOverflow](http://stackoverflow.com/a/18221319/1094484), of course!

**Source code for my little test can be found here (feel free to run it and report back on what you got!):** https://gist.github.com/alberthdev/c81596297efb6ad89d09

My results:
```
$ ~/testsigns 
Is char signed? YES, char is signed
Is int signed? YES, int is signed
CHAR_MIN is -128
INT_MIN is -2147483648
```

So, GCC is clearly expecting both char and int to be signed. So why does it compile happily on GCC? A clue might be to test uint8_t and uint32_t (**2nd test [source code](https://gist.github.com/alberthdev/d02279e32865139f743c)**):
```
$ gcc ~/testsigns_uint.c -o ~/testsigns_uint
/home/albert/testsigns_uint.c: In function ‘main’:
/home/albert/testsigns_uint.c:9:7: error: ‘uint8_t’ undeclared (first use in this function)
  if ((uint8_t)-1 < 0)
       ^
/home/albert/testsigns_uint.c:9:7: note: each undeclared identifier is reported only once for each function it appears in
/home/albert/testsigns_uint.c:15:7: error: ‘uint32_t’ undeclared (first use in this function)
  if ((uint32_t)-1 < 0)

$ clang-3.5 ~/testsigns_uint.c -o ~/testsigns_uint
/home/albert/testsigns_uint.c:9:7: error: use of undeclared identifier 'uint8_t'
        if ((uint8_t)-1 < 0)
             ^
/home/albert/testsigns_uint.c:15:7: error: use of undeclared identifier 'uint32_t'
        if ((uint32_t)-1 < 0)
             ^
2 errors generated.
```

Wait, it doesn't compile! We need `stdint.h` to compile this file, right? Let's hunt for `stdint.h`:

```
grep -r "stdint.h" .
Binary file ./lib/mpir.lib matches
Binary file ./lib/x64/mpir.lib matches
Binary file ./lib/x64/mpir.pdb matches
```

...wait, that's it? Nowhere else? (Note - those libraries are for Windows (Visual Studio) use only - they can't be used by other OSes.)

Well, that means we can't really use uint8_t, right?

```
$ grep -r "uint8_t" .
./modp_ascii.cpp:typedef char uint8_t;
./modp_ascii.cpp:    const uint8_t* ustr = (const uint8_t*) str;
./modp_ascii.cpp:    const uint8_t* ustr = (const uint8_t*) str;
./modp_ascii.cpp:    uint8_t c1,c2,c3,c4;
./modp_ascii.cpp:    const uint8_t* s = (const uint8_t*) str;
```

...so it's just in `modp_ascii.cpp`. Ahhh, I see now... it looks like somehow, your compiler is including `stdint.h` for some reason, causing conflicting definitions. On my side, it's not including this `stdint.h` by default, so the strange definition in `modp_ascii.cpp` takes over and it compiles fine.

For fun, I added `#include <stdint.h>` to the start of `modp_ascii.cpp`, and I got this:
```
g++ -I.  -DUSE_REUSABLES -DUSE_GMP -DUNIXVER -DUSE_BUILTIN_FCREATE -c modp_ascii.cpp
modp_ascii.cpp:45:14: error: conflicting declaration ‘typedef char uint8_t’
 typedef char uint8_t;
              ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.8/include/stdint.h:9:0,
                 from modp_ascii.cpp:3:
/usr/include/stdint.h:48:24: error: ‘uint8_t’ has a previous declaration as ‘typedef unsigned char uint8_t’
 typedef unsigned char  uint8_t;
                        ^
modp_ascii.cpp:46:13: error: conflicting declaration ‘typedef int uint32_t’
 typedef int uint32_t;
             ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.8/include/stdint.h:9:0,
                 from modp_ascii.cpp:3:
/usr/include/stdint.h:51:23: error: ‘uint32_t’ has a previous declaration as ‘typedef unsigned int uint32_t’
 typedef unsigned int  uint32_t;
                       ^
make: *** [modp_ascii.o] Error 1
```
So indeed, the mysterious inclusion of `stdint.h` is causing your error.

Alright, enough talking about investigating, let's attempt a potential solution! (See above!)

**Comment by adriweb** [comment]
That's a long comment :P

But anyway:
* g++ is symlinked to clang++ by default on OS X when developer tools are installed (well, I do have the actual GCC too, if you want me to test that)
* The signedness check did the same as yours, it's signed.
* The "potential fix" did the trick :) Should I make a PR? Well, you could directly change it, actually.
* I guess I could even provide an OS X binary, but oh well, it's very easy to compile... Type make :P
* Here's a photo just to prove it works :+1: 

![84+CE Hello World](https://i.imgur.com/8zr0JRW.jpg)

**Comment by alberthdev** [comment]
Awesome! Could you also check to see if the uint8_t/uint32_t code compiles by itself? (Just to test that theory...)
https://gist.github.com/alberthdev/d02279e32865139f743c

Also, could you try this instead? Replace the previous code with simply:
```
#include <cstdint>
```
I don't feel easy about the previous fix (hence "dirty"), and this is a bit more proper. (Thanks @calc84maniac for the pointer!)

Please test to see if this compiles or not! (And if it works at compiling your test (e)Z80 program!)

**Comment by adriweb** [comment]
The linked source code does compile as-is, already, for all gcc, clang, g++, and clang++

I'm not sure what you want me to try with `#include <cstdint>` though?

**Comment by alberthdev** [comment]
That confirms my suspicion about your compilers - it's automatically including the `stdint.h` file for some reason...

As for `#include <cstdint>`, replace the `#ifdef` mess from before with that single line. Essentially, replace:
```
#ifndef UINT8_MAX
       typedef char uint8_t;
#endif
#ifndef UINT32_MAX
       typedef int uint32_t;
#endif
```
...with just:
```
#include <cstdint>
```

**Comment by adriweb** [comment]
Both compilers wanted `-std=c++11`, then.

But all right, that made it work under clang++.

But g++-4.9 doesn't like it because... 
```
In file included from ./gmp.h:52:0,
                 from stdafx.h:80,
                 from main.cpp:1:
/usr/local/Cellar/gcc/4.9.2_1/include/c++/4.9.2/cstddef:51:11: error: '::max_align_t' has not been declared
   using ::max_align_t;
```

Seems related to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=56019#c1 (also mentioned by https://gcc.gnu.org/gcc-4.9/porting_to.html)

**Comment by alberthdev** [comment]
Hmm. What about this?
```
#include <stdint.h>
```
I think the non-C++ version should work slightly better. (Mixing is fine, and is pretty evident for the entire codebase.)

I'm still trying to figure out what to do. I think `#include <stdint.h>` is plenty good for *nix/OSX, but Windows might be a trickier story. I may end up doing something like this:
```
#if defined(WIN32) || defined(_WIN32) || defined(__WIN32) && !defined(__CYGWIN__)
    typedef unsigned char uint8_t;
    typedef unsigned int uint32_t;
#else
    #include <stdint.h>
#endif
```

**Comment by adriweb** [comment]
Well, in fact it's just a problem with `stdafx.h` and `gmp.h`, not with this `<cstdint>` (or the equivalent C version).
But that might be just my build of GCC 4.9.2...
I mean, it's fine with clang, which is what the makefile will trigger anyway :)

I do confirm that the following still works fine with clang:
```
#if defined(WIN32) || defined(_WIN32) || defined(__WIN32) && !defined(__CYGWIN__)
    typedef unsigned char uint8_t;
    typedef unsigned int uint32_t;
#else
    #include <stdint.h>
#endif
```

**Comment by alberthdev** [comment]
Everything should be good now! If this commit screws up anything, feel free to re-open the issue. (This includes anyone else, especially those building on Windows!)
