### ISSUE TITLE
Unable to Compile

### ISSUE THREAD

**Issue by btryba** [alberthdev/spasm-ng#65]
Hello, 

I cloned the latest version of the the spasm compiler to my Linux Mint machine. I ran the following commands
```
make
sudo make install
```

Success!

Next I downloaded the .inc file from https://en.wikibooks.org/wiki/TI_83_Plus_Assembly/What_you_need (where I found out about spasm). Then I copied the hello world example from the next page (https://en.wikibooks.org/wiki/TI_83_Plus_Assembly/Hello_World).

When I run: `spasm Hello.asm` the output I get is:

```
Hello.asm:9: warning: redefinition of 'LD'
/home/btryba/Desktop/Hello/ti83plus.inc:1384: warning: previous definition of 'LD' was here
Hello.asm:9: error SE113: Unknown opcode 'a'
Hello.asm:10: error SE119: Unknown syntax
Hello.asm:11: error SE119: Unknown syntax
Hello.asm:12: error SE113: Unknown opcode 'hl'
Hello.asm:13: error SE113: Unknown opcode 'B_CALL'
Hello.asm:14: error SE113: Unknown opcode 'B_CALL'
```

I have previously assembled using TASM on windows way back in the day and I'm excited that spasm just does everything so you don't need to do the DevPac8x stuff. I'm looking forward to getting this to work. Thanks for the help!

**Comment by calc84maniac** [comment]
The "redefinition of LD" sounds like you didn't indent your code, so the ld instruction is being treated as a label definition. Since you're not assembling with the case-sensitive flag (which I do recommend using) this conflicts with the lD equate in the include file.

The B_CALL errors are likely due to include file differences, you'll probably find that your include file defines it as bcall.

**Comment by btryba** [comment]
Perfect! I didn't realize having the code tabbed over was important. Thank you for the effort in this project, it is great to have!
